name: env_24_SIGIR_DFF
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
    - datasets
    - gensim
    - ir-datasets
    - matplotlib
    - matplotlib-inline
    - nltk
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - seaborn
