name: virtual_env_24_SIGIR_DFF
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
    - datasets==2.14.5
    - gensim==4.3.0
    - ir-datasets==0.5.5
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.6
    - nltk==3.8.1
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - seaborn
